version: '3.8'

services:
  app1: 
    build: .
    container_name: app1
    ports:
      - "8081:8080"
  
  app2:
    build: .
    container_name: app2
    ports:
      - "8082:8080"

  nginx: 
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
      depends_on:
        - app1
        - app2
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf    